export { computeQuote } from './compute.js';
export {
  bandTotal,
  countingTiers,
  coveredBySuite,
  engagementPct,
  moduleById,
  packDiscFor,
  packPrice,
  phBandIdx,
  phGradSEK,
  phLadder,
  segmentFor,
  selectedPackOf,
  suiteCovers,
} from './engine.js';
export type {
  AiCredit,
  Band,
  Fee,
  Leg,
  Module,
  OneTimeLine,
  Pack,
  PackPrice,
  PriceBook,
  QuoteInput,
  QuoteResult,
  Segment,
  ServiceLine,
  SubscriptionLine,
} from './types.js';
