/**
 * The list of charges Zuora is missing.
 *
 * The new pricing does not exist in the Zuora catalogue yet, so every charge in
 * the price book has nothing behind it. This writes that out as two artifacts:
 *
 *   packages/pricing/data/zuora-mapping.v137.csv   the spreadsheet to fill in
 *   docs/zuora-charges-required.md                 the same thing, readable
 *
 * Fill the two id columns in the CSV, commit it, and `billingReadiness` starts
 * reporting those charges as billable. Nothing here invents a Zuora id.
 *
 *   pnpm zuora:template           # write
 *   pnpm zuora:template --check   # fail if either artifact is out of date
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { billingReadiness, catalogCharges, chargeTemplateCsv, parseMappingCsv } from '../packages/pricing/src/index.js';
import type { CatalogLink, PriceBook } from '../packages/pricing/src/index.js';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const BOOK = join(root, 'packages/pricing/data/price-book.v137.json');
const CSV = join(root, 'packages/pricing/data/zuora-mapping.v137.csv');
const REPORT = join(root, 'docs/zuora-charges-required.md');
const check = process.argv.includes('--check');

const book = JSON.parse(readFileSync(BOOK, 'utf8')) as PriceBook;

// Keep whatever has already been filled in; this tool only ever adds rows.
const existing = (() => {
  try {
    return parseMappingCsv(readFileSync(CSV, 'utf8'));
  } catch {
    return [];
  }
})();
const link: CatalogLink = { priceBookVersionId: 'v137', mappings: existing };

const csv = chargeTemplateCsv(book, link);
const readiness = billingReadiness(book, link);

const byKind = (kind: string): string[] =>
  catalogCharges(book)
    .filter((c) => c.kind === kind)
    .map((c) => {
      const done = readiness.mapped.some((m) => m.key === c.key);
      return `| ${done ? '✅' : '—'} | \`${c.key}\` | ${c.name} | ${c.zuoraChargeModel} | ${c.unit ?? ''} |`;
    });

const section = (title: string, kind: string, note: string): string =>
  [
    `## ${title}`,
    '',
    note,
    '',
    '| In Zuora | Key | Name | Charge model | Quantity counts |',
    '|---|---|---|---|---|',
    ...byKind(kind),
    '',
  ].join('\n');

const report = [
  '# Charges Zuora needs',
  '',
  '> Generated by `pnpm zuora:template`. Do not edit — fill in',
  '> `packages/pricing/data/zuora-mapping.v137.csv` instead and regenerate.',
  '',
  `Price book **v137**. ${readiness.mapped.length} of ${readiness.total} charges exist in Zuora.`,
  '',
  readiness.billable
    ? 'Every charge in the price book has a Zuora charge behind it.'
    : `**${readiness.unmapped.length} charges cannot be invoiced yet.** The new pricing has not been ` +
      'built in the Zuora catalogue, so until these exist a quote can be produced and signed but not billed.',
  '',
  'Fill `product_rate_plan_id` and `product_rate_plan_charge_id` in the CSV for each row. A row with',
  'only one of the two is treated as unfinished, not as a mapping.',
  '',
  section('Subscription charges', 'subscription', 'Priced by the engine from the quote. The quantity is committed at order time.'),
  section('Recurring services', 'recurring-service', 'A flat fee every year, independent of headcount.'),
  section('One-time charges', 'one-time', 'Charged once on the initial order.'),
  '## Still to decide',
  '',
  '- **Does the suite bill as one charge or as its members?** A quote shows Full Suite as a single',
  '  line, so it is one charge here. If Zuora needs the members itemised for revenue recognition,',
  '  that changes the mapping and the quote document.',
  '- **The predictive-hiring size charge and Pro extras are legs inside the pack total**, not lines of',
  '  their own. If they need to be separately invoiced, they need their own charges.',
  '- **Which Zuora identifier is stable enough to key on** — the ids here are whatever goes in the CSV.',
  '',
].join('\n');

if (check) {
  const stale = [
    readFileSync(CSV, 'utf8') !== csv ? 'zuora-mapping.v137.csv' : null,
    readFileSync(REPORT, 'utf8') !== report ? 'zuora-charges-required.md' : null,
  ].filter(Boolean);
  if (stale.length) {
    console.error(`Out of date: ${stale.join(', ')}. Run \`pnpm zuora:template\` and commit the result.`);
    process.exit(1);
  }
  console.log(`Zuora mapping artifacts are current (${readiness.mapped.length}/${readiness.total} charges mapped).`);
} else {
  writeFileSync(CSV, csv);
  writeFileSync(REPORT, report);
  console.log(
    `${readiness.total} charges in v137; ${readiness.mapped.length} mapped, ${readiness.unmapped.length} still missing from Zuora.`,
  );
}
